title: Gifted NFT
logo: /assets/img/synth-logo-xs.png
description: Minimal is a theme for GiftedNFT Project.
show_downloads: false
is_project_page: true
google_analytics: false
theme: jekyll-theme-minimal
